spring.application.name=spring-jwt-basic

server.port=8080

#app.auth.username=alex
#app.auth.password=1234

app.jwt.secret=mi_clave_secreta_para_firmar_el_token
app.jwt.expiration=3600000  # 1 hora en milisegundos